/* =============================================================================
   CAREER · CONTENT — Acciones de carrera
   Las acciones que el jugador gasta en precampaña (distintas a las acciones de
   campaña electoral del gameStore). Cada una cuesta puntos y produce efectos.
   ============================================================================= */

import type { CareerActionDefinition, CareerActionKind } from '../types';

export const CAREER_ACTIONS: Record<CareerActionKind, CareerActionDefinition> = {
  build_alliance: {
    kind: 'build_alliance',
    label: 'Construir alianza',
    description: 'Acercarte a un NPC y subir su confianza.',
    icon: '🤝',
    cost: 2,
    requiresRegion: false,
    requiresNpc: true,
  },
  meet_regional_leader: {
    kind: 'meet_regional_leader',
    label: 'Visitar a un líder regional',
    description: 'Visita formal a una provincia. Sube apoyo local.',
    icon: '📍',
    cost: 1,
    requiresRegion: true,
    requiresNpc: false,
  },
  accept_donor: {
    kind: 'accept_donor',
    label: 'Aceptar apoyo de donante',
    description: 'Conseguir caja a cambio de un favor futuro.',
    icon: '$',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
  reject_controversial_donor: {
    kind: 'reject_controversial_donor',
    label: 'Rechazar donante controversial',
    description: 'Gesto público de transparencia.',
    icon: '✕',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
  shift_ideology: {
    kind: 'shift_ideology',
    label: 'Reposicionar ideología',
    description: 'Mover el discurso hacia el centro o los extremos.',
    icon: '⇌',
    cost: 2,
    requiresRegion: false,
    requiresNpc: false,
  },
  found_movement: {
    kind: 'found_movement',
    label: 'Fundar movimiento propio',
    description: 'Cortar con el partido y crear estructura propia.',
    icon: '⚑',
    cost: 4,
    requiresRegion: false,
    requiresNpc: false,
  },
  negotiate_endorsement: {
    kind: 'negotiate_endorsement',
    label: 'Negociar aval institucional',
    description: 'Conseguir respaldo de la dirigencia.',
    icon: '◈',
    cost: 2,
    requiresRegion: false,
    requiresNpc: false,
  },
  denounce_corruption: {
    kind: 'denounce_corruption',
    label: 'Denunciar corrupción',
    description: 'Postura de transparencia con costo político.',
    icon: '⚖',
    cost: 2,
    requiresRegion: false,
    requiresNpc: false,
  },
  moderate_discourse: {
    kind: 'moderate_discourse',
    label: 'Moderar discurso',
    description: 'Bajar radicalismo, subir credibilidad económica.',
    icon: '↘',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
  radicalize_discourse: {
    kind: 'radicalize_discourse',
    label: 'Radicalizar discurso',
    description: 'Subir polarización, conectar con base movilizada.',
    icon: '↗',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
  keep_promise: {
    kind: 'keep_promise',
    label: 'Cumplir una promesa',
    description: 'Cerrar un compromiso pendiente.',
    icon: '✓',
    cost: 2,
    requiresRegion: false,
    requiresNpc: false,
  },
  abandon_promise: {
    kind: 'abandon_promise',
    label: 'Abandonar una promesa',
    description: 'Sacársela de encima públicamente.',
    icon: '×',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
  support_ally: {
    kind: 'support_ally',
    label: 'Apoyar a un aliado',
    description: 'Gastar capital político en favor de un aliado.',
    icon: '↑',
    cost: 1,
    requiresRegion: false,
    requiresNpc: true,
  },
  betray_ally: {
    kind: 'betray_ally',
    label: 'Traicionar a un aliado',
    description: 'Cortar lazos a cambio de un beneficio inmediato.',
    icon: '⚔',
    cost: 1,
    requiresRegion: false,
    requiresNpc: true,
  },
  prepare_candidacy: {
    kind: 'prepare_candidacy',
    label: 'Preparar candidatura',
    description: 'Foco directo al armado electoral del ciclo.',
    icon: '★',
    cost: 1,
    requiresRegion: false,
    requiresNpc: false,
  },
};

export const CAREER_ACTION_DECK: readonly CareerActionKind[] = [
  'meet_regional_leader',
  'build_alliance',
  'prepare_candidacy',
  'moderate_discourse',
  'radicalize_discourse',
  'keep_promise',
  'negotiate_endorsement',
  'denounce_corruption',
];
