/* =============================================================================
   PARTY · CONTENT — Catálogo de acciones del modo partido
   El jugador gasta puntos de acción en precampaña. Acá vive el catálogo;
   la aplicación de cada acción vive en src/party/actions.ts.
   ============================================================================= */

import type { PartyActionDefinition, PartyActionKind } from '../types';

export const PARTY_ACTIONS: Record<PartyActionKind, PartyActionDefinition> = {
  recruit_candidate: {
    kind: 'recruit_candidate',
    label: 'Reclutar nuevo candidato',
    description: 'Activa un candidato del pool: queda elegible para avales.',
    icon: '+',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: true,
    requiresFaction: false,
  },
  give_endorsement: {
    kind: 'give_endorsement',
    label: 'Otorgar aval',
    description: 'Avala un candidato para la próxima elección. Sube lealtad, baja capital político.',
    icon: '✓',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: true,
    requiresFaction: false,
  },
  revoke_endorsement: {
    kind: 'revoke_endorsement',
    label: 'Revocar aval',
    description: 'Saca el aval — el candidato queda fuera. Baja la lealtad y riesgo de ruptura.',
    icon: '✗',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: true,
    requiresFaction: false,
  },
  open_regional_office: {
    kind: 'open_regional_office',
    label: 'Abrir sede regional',
    description: 'Suma 1 oficina y maquinaria a una provincia. Cuesta caja.',
    icon: '⊞',
    cost: 2,
    requiresRegion: true,
    requiresCandidate: false,
    requiresFaction: false,
  },
  finance_region: {
    kind: 'finance_region',
    label: 'Financiar campaña regional',
    description: 'Inyección de campaña: sube apoyo, militancia y voluntarios en la región.',
    icon: '$',
    cost: 2,
    requiresRegion: true,
    requiresCandidate: false,
    requiresFaction: false,
  },
  accept_donor: {
    kind: 'accept_donor',
    label: 'Aceptar donante condicionado',
    description: 'Aumenta caja con costo reputacional.',
    icon: '⌬',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  reject_donor: {
    kind: 'reject_donor',
    label: 'Rechazar donante sospechoso',
    description: 'No suma caja; sube transparencia percibida.',
    icon: '⊘',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  negotiate_coalition: {
    kind: 'negotiate_coalition',
    label: 'Negociar coalición',
    description: 'Abre una propuesta concreta con un partido. Cierra al avanzar al evento de pacto.',
    icon: '⇄',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  break_coalition: {
    kind: 'break_coalition',
    label: 'Romper coalición activa',
    description: 'Quita una coalición vigente. Cuesta credibilidad pero limpia identidad.',
    icon: '⇶',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  sanction_faction: {
    kind: 'sanction_faction',
    label: 'Sancionar facción interna',
    description: 'Castigo público a una facción: sube disciplina, riesgo de ruptura.',
    icon: '✕',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: true,
  },
  expel_candidate: {
    kind: 'expel_candidate',
    label: 'Expulsar candidato',
    description: 'Quita avales y reduce drásticamente la lealtad del expulsado.',
    icon: '⊠',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: true,
    requiresFaction: false,
  },
  moderate_ideology: {
    kind: 'moderate_ideology',
    label: 'Moderar discurso',
    description: 'Reduce polarización; baja mística de movimiento.',
    icon: '◐',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  radicalize_ideology: {
    kind: 'radicalize_ideology',
    label: 'Radicalizar discurso',
    description: 'Sube polarización y mística de movimiento; cae confianza.',
    icon: '◑',
    cost: 1,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  launch_national_campaign: {
    kind: 'launch_national_campaign',
    label: 'Lanzamiento nacional',
    description: 'Acto + cobertura nacional. Cuesta caja, sube influencia mediática y popular.',
    icon: '◉',
    cost: 3,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  activate_militants: {
    kind: 'activate_militants',
    label: 'Activar militancia',
    description: 'Movilización de bases. Sube voluntarios y apoyo territorial promedio.',
    icon: '⌖',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  resolve_internal_conflict: {
    kind: 'resolve_internal_conflict',
    label: 'Resolver conflicto interno',
    description: 'Bajar tensión entre facciones; sube disciplina y baja rupturas.',
    icon: '⊕',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  distribute_positions: {
    kind: 'distribute_positions',
    label: 'Repartir posiciones',
    description: 'Distribuye cuotas internas: sube lealtad de varias facciones, baja orden.',
    icon: '⊞',
    cost: 2,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
  call_party_congress: {
    kind: 'call_party_congress',
    label: 'Convocar congreso partidario',
    description: 'Ratifica identidad y cohesiona. Sube claridad y disciplina; cuesta caja.',
    icon: '☰',
    cost: 3,
    requiresRegion: false,
    requiresCandidate: false,
    requiresFaction: false,
  },
};

export const PARTY_ACTION_DECK: readonly PartyActionKind[] = [
  'launch_national_campaign',
  'open_regional_office',
  'finance_region',
  'activate_militants',
  'give_endorsement',
  'revoke_endorsement',
  'recruit_candidate',
  'expel_candidate',
  'sanction_faction',
  'resolve_internal_conflict',
  'distribute_positions',
  'call_party_congress',
  'moderate_ideology',
  'radicalize_ideology',
  'negotiate_coalition',
  'break_coalition',
  'accept_donor',
  'reject_donor',
];
